spring.application.name=backend

spring.data.mongodb.host=${mongo.host}
spring.data.mongodb.port=${mongo.port}
spring.data.mongodb.database=${mongo.db}

jwt.secret.key=${secret.key}

merchant.secret=${merchent.secret}
merchant.id=${merchent.id}

# Set this to your ngrok URL when testing (e.g. https://abc123.ngrok-free.app)
payhere.notify.base-url=http://localhost:8080

spring.servlet.multipart.max-file-size=10MB

upload.directory=uploads/
image.upload.directory=postImages/
spring.jackson.time-zone=UTC

logging.level.org.springframework.web=DEBUG
