spring.application.name=backend

spring.data.mongodb.host=${mongo.host}
spring.data.mongodb.port=${mongo.port}
spring.data.mongodb.database=${mongo.db}

jwt.secret.key=${secret.key}

spring.servlet.multipart.max-file-size=10MB

upload.directory=uploads/
spring.jackson.time-zone=UTC

